name: talhadnad
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  provider: ^6.1.2
  url_strategy: ^0.3.0
  dio: ^5.7.0
  json_annotation: ^4.0.0
  http: ^1.2.2
  intl: ^0.17.0
  shared_preferences: ^2.3.2
  flutter_slidable: ^3.1.1
  carousel_slider: ^5.0.0
  dotted_line: ^3.2.2
  table_calendar: ^3.0.8
  image_picker: ^1.0.0
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  ticket_widget: ^1.0.2
  barcode_widget: ^2.0.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
